language: node_js
node_js:
- node
- '10'
- '9'
before_install:
- openssl aes-256-cbc -K $encrypted_02901aa5e03d_key -iv $encrypted_02901aa5e03d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 39.97.226.26\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
