language: node_js
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_02901aa5e03d_key -iv $encrypted_02901aa5e03d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $DEPLOY_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - npm prune --production  # 删除devDependencies
  - docker build -t logicrain/node-web
  - docker login -u $DOCKER-ID -p $DOCKER-PASS
  - docker push logicrain/node-web