language: node_js
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_02901aa5e03d_key -iv $encrypted_02901aa5e03d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $DEPLOY_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - npm prune --production  # 删除devDependencies
  - docker build -t $DOCKER_ID/node-web .
  - docker login -u $DOCKER_ID -p $DOCKER_PASS
  - docker push $DOCKER_ID/node-web
  - ssh root@$DEPLOY_IP 'docker pull logicrain/node-web '
  - ssh root@$DEPLOY_IP 'docker stop node-web '
  - ssh root@$DEPLOY_IP 'docker run --rm --name="node-web" -d -p 80:8080 logicrain/node-web'