language: node_js
node_js:
- node
- '10'
- '9'
before_install:
- openssl aes-256-cbc -K $encrypted_02901aa5e03d_key -iv $encrypted_02901aa5e03d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 39.97.226.26\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - npm prune --production  # 删除devDependencies
  - tar -jcf indoor-server.tar.bz2 *    # 打包并压缩代码
  - scp indoor-server.tar.bz2 root@39.97.226.26:~/  # 复制到生产服务器上
  - ssh root@39.97.226.26 'mkdir -p indoor-server && tar -jxf indoor-server.tar.bz2 -C indoor-server'   # 解压
  - ssh root@39.97.226.26 'cd indoor-server && pm2 startOrReload pm2.json'  